CREATE TABLE Carrier(

	UNIQUE_CARRIER VARCHAR(20),
	AIRLINE_ID INT,
	UNIQUE_CARRIER_NAME VARCHAR(40),
	UNIQUE_CARRIER_ENTITY INT,
	REGION CHAR,
	CARRIER VARCHAR (20),
	CARRIER_NAME VARCHAR(40),
	CARRIER_GROUP INT,
	CARRIER_GROUP_NEW INT,
	PRIMARY KEY (UNIQUE_CARRIER)
);


CREATE TABLE Destination(

	DEST_AIRPORT_ID INT,
	DEST_AIRPORT_SEQ_ID INT,
	DEST_CITY_MARKET_ID INT,
	DEST CHAR,
	DEST_CITY_NAME VARCHAR(40),
	DEST_STATE_ABR VARCHAR(40),
	DEST_STATE_FIPS INT,
	DEST_STATE_NM VARCHAR(30),
	DEST_WAC INT,
	PRIMARY KEY (DEST_AIRPORT_ID)
);


CREATE TABLE Origin(

	ORIGIN_AIRPORT_ID INT,
	ORIGIN_AIRPORT_SEQ_ID INT,
	ORIGIN_CITY_MARKET_ID INT,
	ORIGIN CHAR,
	ORIGIN_CITY_NAME VARCHAR(40),
	ORIGIN_STATE_ABR VARCHAR(40),
	ORIGIN_STATE_FIPS INT,
	ORIGIN_STATE_NM	ORIGIN_WAC INT,
	PRIMARY KEY (ORIGIN_AIRPORT_ID)
);


CREATE TABLE FlightInfo(
	
	AIRLINE_ID INT,
	ORIGIN_AIRPORT_ID INT,
	DEST_AIRPORT_ID INT,
	YEAR INT,
	QUARTER INT,
	MONTH INT,
	DISTANCE_GROUP INT,
	CLASS CHAR,
	PAYLOAD INT,
	SEATS INT,
	PASSENGERS INT,
	FREIGHT INT,
	MAIL INT,
	DISTANCE INT,
	RAMP_TO_RAMP INT,
	AIR_TIME INT,
	FOREIGN KEY (DEST_AIRPORT_ID),
	FOREIGN KEY (ORIGIN_AIRPORT_ID),
	FOREIGN KEY (AIRLINE_ID),
	FOREIGN KEY (AIRCRAFT_TYPE)
);


CREATE TABLE AircraftInfo(

	AIRLINE_ID INT,
	AIRCRAFT_GROUP INT,
	AIRCRAFT_TYPE INT,
	AIRCRAFT_CONFIG INT,
	PRIMARY KEY AIRCRAFT_TYPE
	FOREIGN KEY AIRLINE_ID
);