/*
CS 3810 - Database
Jackson Kolb and Max Morrison
HW3
DUE 10/8/2017 
*/

CREATE TABLE Carrier (
	UNIQUE_CARRIER VARCHAR(10) references Carrier Name(UNIQUE_CARRIER),
	UNIQUE_CARRIER_ENTITY VARCHAR(20) references Carrier_Entity(UNIQUE_CARRIER_ENTITY),
	UNIQUE_CARRIER_NAME VARCHAR(50) references Carrier Abreviation(UNIQUE_CARRIER_NAME)
);

CREATE TABLE Carrier_Entity (
	UNIQUE_CARRIER_ENTITY VARCHAR(10) PRIMARY KEY,
	CARRIER_GROUP VARCHAR(5),
	CARRIER_GROUP_NEW VARCHAR(5),
	REGION VARCHAR(15),
	AIRLINE_ID VARCHAR(10)
);

CREATE TABLE Carrier_Abreviation (
	UNIQUE_CARRIER VARCHAR(10) PRIMARY KEY,
	CARRIER VARCHAR(10)
);

CREATE TABLE Carrier_Name (
	UNIQUE_CARRIER_NAME VARCHAR(50) PRIMARY KEY,
	CARRIER_NAME VARCHAR(50)
);

CREATE TABLE Origin (
	ORIGIN_STATE_NM VARCHAR(20) references Origin_Name(ORIGIN_STATE_NM),
	ORIGIN_AIRPORT_ID VARCHAR(5) references Origin_Airport(ORIGIN_AIRPORT_ID),
	ORIGIN VARCHAR(5) references Origin_City(ORIGIN)
);

CREATE TABLE Origin_Name (
	ORIGIN_STATE_NM	VARCHAR(20) PRIMARY KEY,
	ORIGIN_WAC VARCHAR(5),
	ORIGIN_STATE_FIPS VARCHAR(5),
	ORIGIN_STATE_ABR VARCHAR(5)
);

CREATE TABLE Origin_Airport (
	ORIGIN_AIRPORT_SEQ_ID VARCHAR(15),
	ORIGIN_AIRPORT_ID VARCHAR(5) PRIMARY KEY,
	ORIGIN_CITY_MARKET_ID VARCHAR(10)
);

CREATE TABLE Origin_City (
	ORIGIN_CITY_NAME VARCHAR(30),
	ORIGIN VARCHAR(5) PRIMARY KEY
);

CREATE TABLE Destination (
	DEST_STATE_NM VARCHAR(20) references Destination_Name(DEST_STATE_NM),
	DEST_AIRPORT_ID VARCHAR(5) references Destination_Airport(DEST_AIRPORT_ID),
	DEST VARCHAR(5) references Destination_City(DEST)
);

CREATE TABLE Destination_Airport (
	DEST_AIRPORT_ID VARCHAR(5) PRIMARY KEY,
	DEST_AIRPORT_SEQ_ID VARCHAR(10),
	DEST_CITY_MARKET_ID VARCHAR(5)
);

CREATE TABLE Destination_City (
	DEST_CITY_NAME VARCHAR(20),
	DEST VARCHAR(20) PRIMARY KEY
);

CREATE TABLE Destination_Name (
	DEST_STATE_ABR VARCHAR(5),
	DEST_STATE_FIPS VARCHAR(20),
	DEST_STATE_NM VARCHAR(20) PRIMARY KEY,
	DEST_WAC VARCHAR(3)
);

CREATE TABLE Aircraft (
	AIRCRAFT_GROUP VARCHAR(20),
	AIRCRAFT_TYPE VARCHAR(20),
	AIRCRAFT_CONFIG VARCHAR(20),
	CLASS VARCHAR(5),
	DISTANCE VARCHAR(5) references Aircraft_Distance(DISTANCE),
	DEPARTURES_SCHEDULED VARCHAR(5),
	DEPARTURES_PERFORMED VARCHAR(5)
);

CREATE TABLE Aircraft_Distance (
	DISTANCE_GROUP VARCHAR(5),
	DISTANCE VARCHAR(5) PRIMARY KEY
);

CREATE TABLE Carrier_Code_Dates (
	START_DATE_SOURCE VARCHAR(10),
	THRU_DATE_SOURCE VARCHAR(10),
	UNIQUE_CARRIER_ENTITY VARCHAR(5) PRIMARY KEY
);

CREATE TABLE Aircraft_Passengers (
	SEATS VARCHAR(5) references Aircraft_Seats(SEATS),
	PASSENGERS VARCHAR(5)
);

CREATE TABLE Aircraft_Airtime (
	RAMP_TO_RAMP VARCHAR(5),
	AIR_TIME VARCHAR(5),
	DISTANCE VARCHAR(5) references Aircraft_Distance(DISTANCE)
);

CREATE TABLE Time_of (
	YEAR VARCHAR(10),
	MONTH VARCHAR(10),
	QUARTER(10)
);

CREATE TABLE Aircraft_Seats (
	SEATS VARCHAR(5) PRIMARY KEY,
	AIRCRAFT_CONFIG(5)
);

CREATE TABLE Aircraft_Payload (
	PAYLOAD VARCHAR(10),
	FREIGHT VARCHAR(10),
	MAIL VARCHAR(10)
);

